<h1>
	Add to Watchlist
	<a href='<?php echo $this->url->get(['for' => 'watchlist all']);?>'>*</a>
</h1>
<!-- ul>
<?php
?>
<?php foreach ($watchlist as $wMovie): ?>
	<?php $movie = $wMovie["movie"]; ?>
	<li><?php echo $movie->title; ?>
		<?php if (isset($movie->rating)): ?>
		[<?php echo $movie->rating; ?>]
		<?php endif; ?>
		<a href="<?php echo $this->url->get(['for' => 'watched add', 'movie_id' => $movie->_id]); ?>">[mark as watched]</a>
		<a href="<?php echo $this->url->get(['for' => 'watchlist delete', 'movie_id' => $movie->_id]); ?>">[forget it]</a>
	</li>
<?php endforeach; ?>
</ul-->

<?php if ($success): //TODO: Actually display errors and success by flash messages. ?>
<p>Added <span class="movie_title"><?php echo $addedMovie->title; ?></span>. Add another?</p>
<?php endif; ?>
<?php if ($error): ?>
<p>Error ($error). Try again?</p>
<?php endif; ?>

<p>add form</p>
<form method="post">
	<div><label>Title</label> <input name="title" /></div>
<p>Field: Movie: On /*focus*/ change, if > 3 letters, Ajax (no more than 1 request at a time) any matching movie, display on the side. Clicking the movie enters the IMDB ID in the field.</p>
	<div><label>IMDB ID</label> <input name="imdb" /></div>
	<div><label>rating</label> <input name="rating" /></div>
	<p>Helper: This regers how eager you are to watch the movie, and will be used to make recommendations.</p>
	<p>TODO: star selector.</p>
	<input type="submit" />
</form>
