<h1>
	Watchlist
	<a href='<?php echo $this->url->get(['for' => 'watchlist add']);?>'>+</a>
</h1>
<ul>
<?php
/*
$this->url->get(['for' => 'watched']),
$this->url->get(['for' => 'watched', 'test' => 'test']),
$this->url->get(['for' => 'watched', 'test' => 123]),
$this->url->get(['for' => 'watched', 'movie_id' => $movie->_id])
*/
?>
<?php foreach ($watchlist as $movie) { ?>
	<li><?php echo $movie->title; ?>
		<a href="<?php echo $this->url->get(['for' => 'watched add', 'movie_id' => $movie->_id]); ?>">[mark as watched]</a>
		<a href="<?php echo $this->url->get(['for' => 'watchlist delete', 'movie_id' => $movie->_id]); ?>">[forget it]</a>
	</li>
<?php
//$url = $this->url->get(['for' => 'homepage']);
//$a_tag = $this->tag->linkTo(array(array('for' => 'homepage', 'id' => 'backLink'), 'back to homepage'));
?>
<?php } ?>
</ul>
