<?php
Phalcon\Tag::setDefault('name', $user->name);
Phalcon\Tag::setDefault('email', $user->email);
?>
Profile Info

<?php echo Phalcon\Tag::form(array('', 'method' => 'post')); ?>

    <label for="name">Name</label>
    <?php echo Phalcon\Tag::textField(array('name')); ?>

    <label for="email">Email</label>
    <?php echo Phalcon\Tag::textField(array('email')); ?>

    <p>Change Password:</p>
    <label for="current-password">Current:</label>
    <?php echo Phalcon\Tag::passwordField(array('current-password')); ?>
    <label for="new-password">New:</label>
    <?php echo Phalcon\Tag::passwordField(array('new-password')); ?>
    <label for="again-password">New again:</label>
    <?php echo Phalcon\Tag::passwordField(array('again-password')); ?>

    <?php echo Phalcon\Tag::submitButton('Save'); ?>

<?php echo Phalcon\Tag::endForm(); ?>

