<?php
$user = $this->session->getUser();
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Watchlist</title>
<?php echo $this->head->styles()->get(); ?>
</head>
<body>
<header class="main-menu">
  <nav>
    <ul>
      <li>
        <a href="<?php echo $this->url->get(['for' => 'top']); ?>" class="logo">CLS</a>
      </li>
    </ul>
    <ul>
      <li><a href="<?php echo $this->url->get(['for' => 'top']); ?>">Top</a></li>
      <?php if (empty($user)): ?>
      <li><a href="<?php echo $this->url->get(['for' => 'login']); ?>">Login</a></li>
      <li><a href="<?php echo $this->url->get(['for' => 'register']); ?>">Register</a></li>
      <?php else: ?>
      <li><a href="<?php echo $this->url->get(['for' => 'watchlist top']); ?>">Watchlist</a></li>
      <li class="menu-item">
        <i class="fa fa-user"></i> <?php echo $user->name; ?>
        <ul>
          <li><a href="<?php echo $this->url->get(['for' => 'logout']); ?>"><i class="fa fa-btn fa-power-off"></i> Logout</a></li>
          <li><a href="<?php echo $this->url->get(['for' => 'user profile']); ?>">My Account</a></li>
        </ul>
      </li>
      <?php endif; ?>
    </ul>
  </nav>
</header>

<div class="flash">
    Flash
    <?php $this->flash->output(); ?>
    <?php //$messages = $this->flash->getMessages(); ?>
    <?php //$this->flash->clear(); ?>
</div>

<main>
<?php echo $this->getContent() ?>
</main>

<aside></aside>

<footer><nav><a href="https://github.com/chyro/CLS">Github</a></nav></footer>

<?php echo $this->head->scripts()->get(); ?>
</body>
</html>
