<?php
$user = $this->session->getUser();
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Watchlist</title>
<?php echo $this->head->styles()->get(); ?>
</head>
<body>
<header>
    <a href="<?php echo $this->url->get(['for' => 'top']); ?>" class="logo">CLS</>
    <nav>
        <a href="<?php echo $this->url->get(['for' => 'top']); ?>">Top</a>
        <?php if (empty($user)): ?>
        <a href="<?php echo $this->url->get(['for' => 'login']); ?>">Login</a>
        <a href="<?php echo $this->url->get(['for' => 'register']); ?>">Register</a>
        <?php else: ?>
        <a href="<?php echo $this->url->get(['for' => 'watchlist all']); ?>">Watchlist</a>
        <a>as <?php echo $user->name; ?></a>
        <a href="<?php echo $this->url->get(['for' => 'logout']); ?>">Logout</a>
        <a href="<?php echo $this->url->get(['for' => 'user profile']); ?>">My Account</a>
        <?php endif; ?>
    </nav>
</header>

<div class="flash">
    Flash
    <?php $this->flash->output(); ?>
    <?php //$messages = $this->flash->getMessages(); ?>
    <?php //$this->flash->clear(); ?>
</div>

<main>
<?php echo $this->getContent() ?>
</main>

<aside></aside>

<footer><nav><a href="https://github.com/chyro/CLS">Github</a></nav></footer>

<?php echo $this->head->scripts()->get(); ?>
</body>
</html>
